/**
 * One-time import of the six JSON ledgers from the old app into D1.
 *
 * Reads the legacy files, emits SQL, and writes it to `seed.sql`. Nothing is
 * executed against a database here -- you review the SQL, then apply it:
 *
 *   bun run scripts/import-ledgers.ts
 *   wrangler d1 execute studioos-db --local  --file=./seed.sql
 *   wrangler d1 execute studioos-db --remote --file=./seed.sql
 *
 * Deliberately a separate reviewable step rather than an automatic migration:
 * this is the studio's only copy of data that exists nowhere in ERPNext, and a
 * silent import that half-worked would be worse than no import.
 *
 * Run this with `bun`, not in a Worker -- it needs the filesystem.
 */

import { readFileSync, writeFileSync } from 'node:fs';
import { join } from 'node:path';

const LEGACY = join(
  import.meta.dir,
  '..',
  '..',
  '..',
  'Erpnext UI Application',
  'CSDSxERPnext App',
  'server',
  'data',
);

/** SQLite string literal. Doubling single quotes is the only escape it needs. */
function q(value: unknown): string {
  if (value === null || value === undefined) return 'NULL';
  if (typeof value === 'number') return Number.isFinite(value) ? String(value) : '0';
  if (typeof value === 'boolean') return value ? '1' : '0';
  return `'${String(value).replace(/'/g, "''")}'`;
}

function read<T>(file: string): T {
  return JSON.parse(readFileSync(join(LEGACY, file), 'utf8')) as T;
}

const out: string[] = [
  '-- Generated by scripts/import-ledgers.ts. Review before applying.',
  'PRAGMA foreign_keys = ON;',
  '',
];

// --- expenses -------------------------------------------------------------
const expensesData = read<{ expenses: Record<string, unknown>[] }>('projectExpenses.json');
for (const e of expensesData.expenses ?? []) {
  out.push(
    `INSERT OR REPLACE INTO expenses (id, project, date, category, description, amount, estimated_amount, paid_by, mode, created_at) VALUES (${[
      q(e.id),
      q(e.project),
      q(e.date),
      q(e.category),
      q(e.description ?? ''),
      q(Number(e.amount) || 0),
      q(Number(e.estimatedAmount) || 0),
      q(e.paidBy ?? ''),
      q(e.mode ?? 'Cash'),
      q(e.createdAt ?? e.date),
    ].join(', ')});`,
  );
}

// --- crew -----------------------------------------------------------------
const crewData = read<{ entries: Record<string, unknown>[] }>('projectCrew.json');
for (const c of crewData.entries ?? []) {
  out.push(
    `INSERT OR REPLACE INTO crew_entries (id, project, role, name, designation, rate, days, total, contact, notes, created_at) VALUES (${[
      q(c.id),
      q(c.project),
      q(c.role ?? 'Crew'),
      q(c.name),
      q(c.designation ?? ''),
      q(Number(c.rate) || 0),
      q(Number(c.days) || 0),
      q(Number(c.total) || 0),
      q(c.contact ?? ''),
      q(c.notes ?? ''),
      q(c.createdAt ?? ''),
    ].join(', ')});`,
  );
}

// --- subscriptions --------------------------------------------------------
const subsData = read<{ subscriptions: Record<string, unknown>[] }>('subscriptions.json');
for (const s of subsData.subscriptions ?? []) {
  out.push(
    `INSERT OR REPLACE INTO subscriptions (id, name, category, vendor, amount, currency, cycle, next_due, payment_mode, billed_to, active, notes, created_at) VALUES (${[
      q(s.id),
      q(s.name),
      q(s.category ?? ''),
      q(s.vendor ?? ''),
      q(Number(s.amount) || 0),
      q(s.currency ?? 'INR'),
      q(s.cycle ?? 'Monthly'),
      q(s.nextDue ?? ''),
      q(s.paymentMode ?? ''),
      q(s.billedTo ?? ''),
      q(Boolean(s.active)),
      q(s.notes ?? ''),
      q(s.createdAt ?? ''),
    ].join(', ')});`,
  );
}

// --- transactions ---------------------------------------------------------
// Existing integer ids are preserved so anything referencing them still lines
// up; SQLite's AUTOINCREMENT continues from the highest imported id.
const txData = read<{ transactions: Record<string, unknown>[] }>('transactions.json');
for (const t of txData.transactions ?? []) {
  out.push(
    `INSERT OR REPLACE INTO transactions (id, project, date, amount, direction, type, description, mode, source) VALUES (${[
      q(Number(t.id)),
      q(t.project ?? null),
      q(t.date),
      q(Number(t.amount) || 0),
      q(t.direction),
      q(t.type ?? ''),
      q(t.description ?? ''),
      q(t.mode ?? ''),
      q(t.source ?? 'manual'),
    ].join(', ')});`,
  );
}

// --- studio rental (bookings + nested sessions) ---------------------------
const rentalData = read<{ bookings: Record<string, unknown>[] }>('studioRental.json');
for (const b of rentalData.bookings ?? []) {
  out.push(
    `INSERT OR REPLACE INTO rental_bookings (id, client, poc, tag, rate_type, rate, billing_cycle, notes) VALUES (${[
      q(b.id),
      q(b.client),
      q(b.poc ?? ''),
      q(b.tag ?? ''),
      q(b.rateType ?? 'hourly'),
      q(Number(b.rate) || 0),
      q(b.billingCycle ?? ''),
      q(b.notes ?? ''),
    ].join(', ')});`,
  );

  for (const s of (b.sessions as Record<string, unknown>[]) ?? []) {
    out.push(
      `INSERT OR REPLACE INTO rental_sessions (id, booking_id, date, time_in, time_out, hours, rounded_hours, amount, paid, payment_date, invoice_ref) VALUES (${[
        q(s.id),
        q(b.id),
        q(s.date),
        q(s.timeIn ?? ''),
        q(s.timeOut ?? ''),
        q(Number(s.hours) || 0),
        q(Number(s.roundedHours) || 0),
        q(Number(s.amount) || 0),
        q(Boolean(s.paid)),
        q(s.paymentDate ?? null),
        q(s.invoiceRef ?? null),
      ].join(', ')});`,
    );
  }
}

// --- brand (single row) ---------------------------------------------------
const brandData = read<Record<string, any>>('brand.json');
out.push(
  `INSERT OR REPLACE INTO brand (id, company_name, tagline, logo_path, accent_color, address_line1, address_line2, address_line3, address_country, phone, email, bank_account_name, bank_name, bank_account_no, bank_branch, bank_ifsc, bank_pan, upi_id, show_qr, show_bank_details, notes_title, notes, footer_text) VALUES (${[
    1,
    q(brandData.companyName ?? ''),
    q(brandData.tagline ?? ''),
    q(brandData.logoPath ?? ''),
    q(brandData.accentColor ?? '#3d7fa6'),
    q(brandData.address?.line1 ?? ''),
    q(brandData.address?.line2 ?? ''),
    q(brandData.address?.line3 ?? ''),
    q(brandData.address?.country ?? ''),
    q(brandData.phone ?? ''),
    q(brandData.email ?? ''),
    q(brandData.bank?.accountName ?? ''),
    q(brandData.bank?.bankName ?? ''),
    q(brandData.bank?.accountNo ?? ''),
    q(brandData.bank?.branch ?? ''),
    q(brandData.bank?.ifsc ?? ''),
    q(brandData.bank?.pan ?? ''),
    q(brandData.upiId ?? ''),
    q(Boolean(brandData.showQr)),
    q(Boolean(brandData.showBankDetails)),
    q(brandData.notesTitle ?? 'Notes'),
    q(brandData.notes ?? ''),
    q(brandData.footerText ?? ''),
  ].join(', ')});`,
);

const target = join(import.meta.dir, '..', 'seed.sql');
writeFileSync(target, out.join('\n') + '\n', 'utf8');

console.log(`Wrote ${out.length - 3} INSERT statements to ${target}`);
console.log('Review it, then:');
console.log('  wrangler d1 execute studioos-db --local  --file=./seed.sql');
console.log('  wrangler d1 execute studioos-db --remote --file=./seed.sql');
